### ISSUE TITLE
수정 API를 수정

### ISSUE THREAD

**Issue by Muokok** [FACETICKER/server#153]
호스트 포스터 수정
- [x]  PATCH 말고 PUT으로 받아오기 
- [x]  사랑 vs 우정 조회 후 사자성어 등록 -> 만약 DB에 저장된 것이 사랑인데 사랑이 또 들어왔다고 사자성어 수정되면 X

호스트 스티커 수정
- [x]  PATCH 말고 PUT으로 변경
- [x]  final_image 변경

- [x] 응답 형식 수정

포스터, 스티커 수정의 응답을 수정된 내용을 포함한 전체적인 데이터를 반환하도록 수정함

**Comment by seungheon123** [comment]
- [ ] PUT에서 PATCH로 다시 변경
- [ ] 스티커 수정에서 final 값만 받아오기 X. 전체 스티커 아이디 + final 받아오기
